package kaiquebt.dev.instrutorbrasil.model.enums;

public enum ErrorCode {
	// Generic errors
	INTERNAL_SERVER_ERROR,
	VALIDATION_ERROR,
	RESOURCE_NOT_FOUND,
	UNAUTHORIZED,
	FORBIDDEN,
	RATE_LIMIT_EXCEEDED,

	// Authentication errors
	INVALID_CREDENTIALS,
	TOKEN_EXPIRED,
	TOKEN_INVALID,
	EMAIL_ALREADY_EXISTS,
	EMAIL_NOT_VERIFIED,
	INVALID_PROVIDER,

	// Onboarding errors
	ONBOARDING_ALREADY_IN_PROGRESS,
	ONBOARDING_NOT_FOUND,
	ONBOARDING_ALREADY_SUBMITTED,
	ONBOARDING_NOT_IN_REVIEW,
	ONBOARDING_PERMANENTLY_REJECTED,
	ONBOARDING_RETRY_COOLDOWN,
	ONBOARDING_CANNOT_ADD_DOCUMENTS,

	// Document errors
	DOCUMENT_NOT_FOUND,
	DOCUMENT_ALREADY_EXISTS,
	DOCUMENT_CONFLICT,
	DOCUMENT_INVALID_TYPE,
	REQUIRED_DOCUMENTS_MISSING,

	// User errors
	USER_NOT_FOUND,
	USER_ALREADY_INSTRUCTOR,

	// Request errors
	INVALID_REQUEST,
	MISSING_REQUIRED_FIELD,
	INVALID_FIELD_FORMAT,
	INVALID_FIELD_VALUE
}
